services:
  back-end-aluguequadras-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: back-end-aluguequadras:production
    container_name: back-end-aluguequadras-production
    restart: unless-stopped
    ports:
      - "3000:3000"
    command: ["node", "-r", "dotenv/config", "dist/src/main.js", "dotenv_config_path=env/production.env"]
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true
