# ============================
# PGPool PCP
# ============================
listen_addresses = '*'
port = 5432

pcp_listen_addresses = '*'
pcp_port = 9898

listen_backlog_multiplier = 2
serialize_accept = off

# ============================
# Configuração Gerais
# ============================

enable_pool_hba = off
allow_clear_text_frontend_auth = on

# ============================
# não alterar
# pool_passwd = '/etc/pgpool2/pool_passwd'
# pool_hba_file = '/etc/pgpool2/pool_hba.conf'
backend_status_file = '/var/log/postgresql/pgpool_status'
unix_socket_dir = '/var/run/pgpool2'
pcp_socket_dir = '/var/run/pgpool2'

allow_sql_comments = on
authentication_timeout = 30

ignore_leading_white_space = on

# ============================
# Configuração do BACKEND
# ============================
num_init_children = 32

max_pool = 100

sr_check_user = 'postgres'
sr_check_password = 'postgres'

load_balance_mode = on

backend_clustering_mode = 'streaming_replication'

backend_hostname0 = '192.168.1.3'
backend_port0 = '5433'
backend_weight0 = 0 
backend_flag0 = 'ALLOW_TO_FAILOVER'
backend_user0 = 'postgres'
backend_password0 = 'postgres'

backend_hostname1 = '192.168.1.3'
backend_port1 = '5434'
backend_weight1 = 2
backend_flag1 = 'ALLOW_TO_FAILOVER'
backend_user1 = 'postgres'
backend_password1  = 'postgres'

# ============================
# Configuração do FAILOVER / FAILBACK (Atualmente o patroni está responsavel)
# ============================

failover_on_backend_error = off

# somente com +3 instancias pgpool (c/ whatdog)
# failover_when_quorum_exists = on
# failover_require_consensus = on

# failover_command = '/etc/pgpool/failover.sh %d %h %p %D %m %M'
# failback_command = '/etc/pgpool/failback.sh %d %H %P %R'

# ============================
# Configuração do Watchdog (apenas para 2 instancias)
# https://www.pgpool.net/docs/pgpool-II-4.3.4/en/html/watchdog-configuration.html
# ============================

# pgpool_node_id = 0

# # Ativar Watchdog
# use_watchdog = on

# # # Configurações do pgpool0
# hostname0 = '' # Substitua pelo IP da máquina
# wd_port0  = 9000
# pgpool_port0 = 5430

# # Configurações do pgpool1
# hostname1 = '' # Substitua pelo IP da máquina
# wd_port1  = 9001
# pgpool_port1 = 5431

# ============================
# Configuração do Virtual IP (VIP)
# ============================

# delegate_IP = ''  # Ou remova essa linha
# if_cmd_path = '/sbin'
# if_up_cmd = ''  # Sem configuração de VIP
# if_down_cmd = ''
# arping_cmd = ''

# ============================
# Configuração do LOG Path
# https://www.pgpool.net/docs/pgpool-II-4.3.4/en/html/runtime-config-logging.html
# ============================

# logging_collector = on  # Ativa a coleta de logs

log_destination = 'stderr'
# log_directory = '/etc/pgpool2/logs'  # Diretório onde os logs serão armazenados
# log_filename = 'pgpool.log'  # Nome do arquivo de log

log_hostname = off  # Registre o nome do host do cliente em vez do endereço IP.
log_statement = off  # Desativa o log de declarações SQL
log_per_node_statement = on  # Registre cada instrução SQL para cada nó do BD separadamente
log_connections = off  # Desativa o log de conexões
